"""empty message

Revision ID: b4b204fdddba
Revises: 7e2e0b4e3760
Create Date: 2019-03-07 21:07:13.622847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b204fdddba'
down_revision = '7e2e0b4e3760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('Publishing', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['front_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
